### ISSUE TITLE
バージョンチェック

### ISSUE THREAD

**Issue by yamcat** [griffin-stewie/atom-redpen#2]
説明に従って，準備を済ませてatomからredpenパッケージを呼び出すと 
redpen package requires RedPenCLI v1 or higher update your RedPenCLI
とはねられてしまいます。
なお，昨日ダウンロードした redpen-cli-1.0 に含まれるredpenのバージョンは0.6です。

**Comment by griffin-stewie** [comment]
RedPen のバージョンが古いため警告が出ています。
こちらからv1.0.1 をインストールしてください。
https://github.com/recruit-tech/redpen/releases/tag/v1.0.1
